version: "3"

services:
  
  library-api:
    build: ./library-api
    volumes:
      - ./library-api:/usr/src/app

    environment:
      - REDIS_ENDPOINT
      - REDIS_USERNAME
      - REDIS_PASSWORD

    ports:
      - 5001:8080

  # movie-library:
  #   image: "redis:alpine"
  #   command: redis-server --requirepass michflix
    
  #   volumes:
  #     - $PWD/redis-data:/var/lib/redis
  #     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  #   ports:
  #   - 6379:6379

  #   environment:
  #     - REDIS_REPLICATION_MODE=master
